# docker build . -t chaincue_real_estate && docker compose up
version: '3.9'

services:
  chaincue_real_estate:
    container_name: chaincue_real_estate
    image: ghcr.io/krispett/chaincue-real-estate:main
    ports:
      - "3001:3000"
