# docker build . -t chaincue_real_estate && docker compose up
# docker compose down
# docker exec -it chaincue_real_estate sh

version: '3.9'

services:
  chaincue_real_estate:
    container_name: chaincue_real_estate
    image: chaincue_real_estate:latest
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
