# docker pull ghcr.io/krispett/chaincue-real-estate:main
# docker compose -f docker-compose-prod.yml up
# docker compose -f docker-compose-prod.yml down
# docker exec -it chaincue_real_estate_prod sh

version: '3.9'

services:
  chaincue_real_estate_prod:
    container_name: chaincue_real_estate_prod
    image: ghcr.io/krispett/chaincue-real-estate:main
    volumes:
      - .env:/app/.env
    ports:
      - "3000:3000"
